### ISSUE TITLE
Comparison with bmalloc?

### ISSUE THREAD

**Issue by clopez** [rampantpixels/rpmalloc#17]
Hi,

I would be interested in a comparison (both in terms of speed and on memory usage) with bmalloc.

https://opensource.apple.com/source/bmalloc/

https://svn.webkit.org/repository/webkit/trunk/Source/bmalloc/

**Comment by MJansson** [comment]
bmalloc added to the benchmark repo, will add results to graphs soon

**Comment by MJansson** [comment]
bmalloc falls too far behind, not going to add it to the graph as it brings no meaningful data to the mix
