### ISSUE TITLE
Considere using a license?

### ISSUE THREAD

**Issue by clopez** [rampantpixels/rpmalloc#18]
IANAL, but It seems that unlicensed can cause issues.

See http://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

As also the tread on https://www.reddit.com/r/programming/comments/63mizt/rpmalloc_a_faster_malloc_public_domain/

If you don't care about licenses, and you just want your software to be used by anyone as broad as possible, then its wiser to chose MIT than this Unlicensed stuff.

MIT will serve the purpose better than Unlicensed.

**Comment by clopez** [comment]
Another option, is CC0.

https://www.gnu.org/licenses/license-list.html#Unlicense

**Comment by seanjensengrey** [comment]
Without a warranty clause the author is actually still liable if it fails. I recommend https://en.wikipedia.org/wiki/MIT_License  as the closest to your goals. 

http://law.stackexchange.com/questions/1410/do-warranty-disclaimers-in-software-licenses-carry-any-legal-weight

**Comment by MJansson** [comment]
Dual license under MIT now available
