### ISSUE TITLE
rpmalloc_initialize() takes over 5 seconds on iOS

### ISSUE THREAD

**Issue by michaeleiselsc** [rampantpixels/rpmalloc#19]
This is on an iPhone 7, and occurs both with -Os and -O0. Here's a picture of what it's doing:
<img width="779" alt="screen shot 2017-04-05 at 10 51 04 pm" src="https://cloud.githubusercontent.com/assets/7732829/24739758/6b36abe4-1a52-11e7-9151-7b88a39dcecc.png">

**Comment by michaeleiselsc** [comment]
It actually hadn't finished at this point. It does finish at some point later

**Comment by MJansson** [comment]
Improved the mmap 64KiB alignment loop a bit, please try and see if it works better for you. I ran the benchmarks on an iPhone5S without getting this problem now.

**Comment by michaeleiselsc** [comment]
works, thanks!
