### ISSUE TITLE
Use extern "C" around header file rpmalloc.h for C++ users

### ISSUE THREAD

**Issue by czipperz** [rampantpixels/rpmalloc#22]
Wrap 

    #ifndef __cplusplus
    extern "C" {
    #endif

and

    #ifndef __cplusplus
    }
    #endif

around rpmalloc.h so that C++ users can link properly

**Comment by LiveAsynchronousVisualizedArchitecture** [comment]
Should this be #ifdef instead of #ifndef ?

**Comment by czipperz** [comment]
Yes

**Comment by czipperz** [comment]
Made a pull.

**Comment by czipperz** [comment]
#24
