### ISSUE TITLE
Comparison with Lockless Inc's Allocator

### ISSUE THREAD

**Issue by ZirconiumHacker** [rampantpixels/rpmalloc#25]
Hi,
I'm interested in benchmarks of how this allocator compares to the Lockless allocator.  I'd also like to know if you have any comments on the way their allocator works compared to yours.  Theirs seems to be based on slabs and b-trees, as well as some form of caching?  The license seems a bit restrictive, but it seems like just including it in an open-source benchmark would be fine.  Disclaimer: IANAL.

https://github.com/VladX/lockless-allocator (a slightly improved, cross-platform version)
http://locklessinc.com/technical_allocator.shtml
http://locklessinc.com/articles/allocator_tricks/

Thanks for this awesome allocator!

**Comment by ZirconiumHacker** [comment]
I know you're probably busy with other things, but I'm overly curious.  What are your thoughts on the Lockless Inc. allocator?  (It's been 3 days, and I'm bored right now.)

**Comment by MJansson** [comment]
I haven't looked at it much since the original source was non-portable. But I got it running on my Linux machine so I'll run the benchmarks and post the results.

**Comment by ZirconiumHacker** [comment]
Alright, thanks.  I'm glad you can continue to work on this project and quickly respond to inquiries; more developers on GitHub should be like you.

**Comment by MJansson** [comment]
Lockless is now added to the benchmark results: https://github.com/rampantpixels/rpmalloc-benchmark/blob/master/BENCHMARKS.md

**Comment by ZirconiumHacker** [comment]
Interesting.  For single-threaded allocation in the last 2 benchmarks, Lockless appears to be faster.  Maybe I'll run some profilers on it.

**Comment by MJansson** [comment]
Yep, larger allocations in a single threaded setting seem to be where lockless works best.
