### ISSUE TITLE
Expand integer range checking to new entry points 

### ISSUE THREAD

**Issue by K2** [rampantpixels/rpmalloc#26]
Include range checking for ENABLE_VALIDATE_ARGS around;

https://github.com/rampantpixels/rpmalloc/blob/master/rpmalloc/malloc.c#L226
and
https://github.com/rampantpixels/rpmalloc/blob/master/rpmalloc/malloc.c#L236

Both cases if the caller assumes they have been returned valid pointers, they would start to over write the heap causing various issues.

**Comment by MJansson** [comment]
Would #27 suffice for validation?

**Comment by K2** [comment]
Yeah looks good, I'll just close it now, thanks
