### ISSUE TITLE
It just crashes

### ISSUE THREAD

**Issue by poige** [rampantpixels/rpmalloc#28]
It crashed with dekstop "workload" (being `/etc/ld.so.preload`'ed) and it crashed with MySQL workload as well. I assume it's not production ready as such.

**Comment by poige** [comment]
Steps to reproduce: have Ubuntu desktop, preload it, watch it's failing. `dmesg` would reveal some details of course

**Comment by MJansson** [comment]
Not every binary is compatible with preloading a malloc replacement. For example, preloading tcmalloc into php gives you a segfault.

Please give concrete examples of binaries where it does not work, with backtraces if possible. Generic reports of "it just crashes" is not very helpful.

If done lots of tests with preloading into mysql without problems. Please post more information.

**Comment by poige** [comment]
> For example, preloading tcmalloc into php gives you a segfault.

Tried many times, none fault given

**Comment by poige** [comment]
> Generic reports of "it just crashes" is not very helpful.

Well, I'm here to indicate some serious issue(s). None of other allocators you're comparing rpmalloc to failed so massively under same circumstances. The only quirk I can mention was jemalloc with emacs — single one for years.

> Please give concrete examples of binaries

As I told you it's just a matter of running desktop Ubuntu with ld.so.preload invoking rpmalloc. It's enough, it's simple and this is something you could easily do by yourself in case you're interesting in having even a slight taste of testing.

**Comment by MJansson** [comment]
rpmalloc is not intended as a blanket system-wide replacement. It is meant as a high performance allocator  for multithreaded applications that can adhere to the limitations imposed.

For example, from the caveats section of the readme: "The free, realloc and usable size functions all require the passed pointer to be within the first 64KiB page block of the start of the memory block. You cannot pass in any pointer from the memory block address range.". This also implies that it does not cope with passing an invalid pointer, it does not try to save the programmer by doing sanity checks of passes paramters.

Also, the libc entry points replacements are meant as a convenience for testing the allocator on an existing binary. They might not be complete. The proper way to use rpmalloc is described in the usage section in the readme.

I've improved the readme in these sections to clarify this.

Now, if you have specific problems with specific binaries you are more than welcome to report this like in #20 , and note the detailed reporting in that issue. That's the way to do it.

**Comment by poige** [comment]
Well, to conclude: PHP with tcmalloc `ld.so.preload`'ed works just fine as my observations show.

**Comment by MJansson** [comment]
Seems php 7 brought some changes. Both tcmalloc and rpmalloc works just fine preloading into php now.

**Comment by poige** [comment]
Well, the changes brought are clearly limited to rpmalloc only. tcmalloc worked and works with 5.6 just fine to me.
