### ISSUE TITLE
Using HugePages

### ISSUE THREAD

**Issue by luben** [rampantpixels/rpmalloc#3]
It would be nice if we can instruct rpmalloc to use HugePages allocation.

At least on linux it's achieved by mmap-ing files from where the hugetlbfs is mounted. So we should be able to configure rpmalloc with the mount point.

Another possible issue: hugepages on x86 come in size of 2MiB, I don't know how it will interact with the 64KiB alignment used by rpmalloc.

**Comment by MJansson** [comment]
I will look into it

**Comment by MJansson** [comment]
Requires #8 in order to handle multiple spans from a single memory mapping

**Comment by MJansson** [comment]
Needs to allow page size > span size, set span map count to fill entire page, and to handle unmapping when page size > span size

**Comment by MJansson** [comment]
@luben Now available in develop branch if you wanna try it out

**Comment by luben** [comment]
Great! Thanks, I will try it

**Comment by luben** [comment]
I think this the better behavior anyway.

**Comment by MJansson** [comment]
1.3.1 released, closing this
