### ISSUE TITLE
EINVAL undeclared on MINGW

### ISSUE THREAD

**Issue by tresf** [rampantpixels/rpmalloc#30]
Reading `rpmalloc.c` it appears as though `EINVAL` is never defined properly for MINGW environments.  I think this is [provided by `<errno.h>`](https://sourceforge.net/p/mingw/mingw-org-wsl/ci/a58a5c2852c7e1ca849453cf89643402f438526a/tree/mingwrt/include/errno.h#l69) but this seems to be [disabled for Win32 builds](https://github.com/rampantpixels/rpmalloc/blob/2592b551b26d0ac9d1c92db3c1ae6c0ce5cd447a/rpmalloc/rpmalloc.c#L1292-L1299).

The build log [is available here](https://travis-ci.org/LMMS/lmms/jobs/286190037#L1072).

**Comment by MJansson** [comment]
Try the latest develop branch, moved the errno.h include to always include (it was not needed for msvc compilation, which is why it was not included in windows builds before).

**Comment by MJansson** [comment]
Btw, in your LMMS PR https://github.com/LMMS/lmms/pull/387 you probably mistyped the thread finalization in `MemoryManager::ThreadGuard::~ThreadGuard()`, see my comment in your PR

**Comment by MJansson** [comment]
If it fixes your build I'll do tests and then a merge to master and a 1.2.1 release to make it easier for you to use as a submodule.

**Comment by MJansson** [comment]
I see the build completed now, but I'll leave this issue open for now until it is merged to master.

**Comment by MJansson** [comment]
Merged to master, closing
