### ISSUE TITLE
Add optional over/underwrite guards

### ISSUE THREAD

**Issue by MJansson** [rampantpixels/rpmalloc#33]
Add compiletime selectable overwrite/underwrite guards for each allocated block to help detect memory corruption issues.

**Comment by iamironz** [comment]
Sorry but what this issue was closed? I cannot found any mentions in code about `ENABLE_GUARDS` define at this time.

**Comment by mjansson** [comment]
There were guards at one point (and thus this was closed). However, the maintenance burden of this extra feature was deemed to high compared to the value of the feature so I removed it. It still exists in the readme since I forgot to remove it.

**Comment by iamironz** [comment]
Got it. So sad. Thank you!
