### ISSUE TITLE
Add support for external allocators

### ISSUE THREAD

**Issue by refnum** [rampantpixels/rpmalloc#39]
We would like to use rpmalloc as an allocator on top of a lower-level page-based allocator, where the low-level allocator provides mmap/munmap-style primitives to obtain pages of memory.

We have some constraints on where in the address space the memory can come from and so this would allow us to have a well-performing allocator (rpmalloc) that could also honour these existing constraints (on where pages can be located).

We have a patch that implements this on our [feral_allocator branch](https://github.com/rampantpixels/rpmalloc/compare/master...FeralInteractive:feral_allocator) but thought it worth discussing before opening a pull request to discuss the design.

The summary is:

- A configuration structure, rpmalloc_config_t, is provided on initialisation to supply mmap/munmap callbacks.
- If no configuration is provided, or if no callbacks are provided, the callbacks default to a VirtualAlloc/mmap implementation.
- Alignment is handled by over-allocating (if necessary) rather than assuming the underlying allocator can honour specific address requests (as, in our case, we can't).

Some discussion of those points:

- A configuration structure could also have a version number, or size field, for backwards source-compatibility. There may also be other configuration-style parameters you would like to add.
- A new initialisation method is added (rpmalloc_initialize_config) but configuration could be added to rpmalloc_initialize with a default parameter if you're assuming C11.
- _memory_map/_memory_unmap now return a pointer and an alignment offset. The alignment offset returned when mapping must be provided when unmapping and so this is stored in each span_t (or the heap_t) along with the other per-map state.
- Another approach from a return parameter would be to declare a 'slab_t' structure that contains this offset, place a slab_t at the start of each span_t/heap_t structure, then rename these methods to _slab_allocate/_slab_free. That would avoid the need to return separate pointer and offset values, and would make both spans and heaps an instance of a 'slab' (where a 'slab' hides the underlying allocator and the alignment logic but can provide a contiguous page range that starts with a slab_t header).
- If the underlying allocator doesn't return a 64KiB-aligned block (VirtualAlloc will, our usage will, mmap might not) then we align by releasing that block and over-allocating by 64KiB. This allows us to support allocators that can return any arbitrary address, and avoids the need for mmap-specific code to track a base address then loop to increment. The downside is that over-allocating can waste up to 16 pages of address space. But, since those alignment pages are never written to they will never be dirtied and so will not increase paging pressure.

**Comment by MJansson** [comment]
I line the idea. Let me have a day to think about it before I get back to you on this topic (and thank you for taking the time to help improve the allocator!)

**Comment by MJansson** [comment]
I would say

- A new entry point `rpmalloc_initialize_config` to avoid breaking the current API
- The alignment offset needs to be stored in the `span_t`. And this needs reshuffling to keep the structure size <= 32 bytes (I don´t want to increase the overhead). There are two unused bytes in the structure (the padding in span_block_t) that can be reshuffled a bit and used.
- map/unmap should use a structure as suggested to return/pass point + offset data. I would not, however, reuse this structure internally to avoid increasing span overhead as mentioned above.
- mmap implementation should be rewritten to use this and get rid of the ugly base pointer bookkeeping

**Comment by MJansson** [comment]
I looked at your implementation, a few issues

- `span_t` overhead is increased to 40 bytes, meaning start of blocks will not be naturally 16-byte aligned which the alignment code assumes. Also, I don't want to increased overhead.
- If the second map call in `_memory_map` returns a 64KiB aligned address, the alignment offset will be 0 and in the end the size passed to underlying unmap function will be wrong (the page count will not be properly increased).

I am tempted to change my previous statement and agree that passing separate pointer & alignment offset to map/unmap is better than a new pair structure.

**Comment by MJansson** [comment]
Untested implementation in configurable-memory-mapper branch, will test and update docs later today

**Comment by refnum** [comment]
I've tested the configurable-memory-mapper branch on top of our pager and that works perfectly, thanks. Two minor edits are:

o In _memory_unmap_os, the first parameter to mmap should be '0' as 'base_addr' no longer exists.
o In _memory_allocate_heap, _memory_config.memory_map takes a byte size rather than a page size so this should be '2 * PAGE_SIZE'.

Alternatively, for the latter, _memory_map could say that the offset parameter was optional and if null then no alignment would be performed. The heap doesn't care where it lives so that would allow _memory_allocate_heap to allocate without doing a page->byte conversion or knowing about the callbacks.

Otherwise all your comments above look good, thanks!

**Comment by MJansson** [comment]
Thanks for the verification. I made the same mistake for unmap of heap and map/unmap of oversized blocks, pushed a fix for this (and the mmap call). Will run the benchmark test suite for verification tonight.

**Comment by MJansson** [comment]
Running the benchmark suite I realized a mistake I made, all memory mappings must be done to 64KiB granularity since for oversized allocs the start is still found by warping pointer to nearest granularity boundary, and for heaps the low 16 bits are used for ABA protection.

**Comment by MJansson** [comment]
Benchmark suite now runs fine on both Windows and Linux, merged to develop branch.
