### ISSUE TITLE
rpMalloc crashing in iOS w/ a 16kb page size

### ISSUE THREAD

**Issue by jritts** [rampantpixels/rpmalloc#41]
I'm trying this library out in an iOS ARKit-based project where I can assume a 16KB page size, however setting the page size to that value in rpmalloc.c causes a crash after a few allocations:

   988		if (*cache)
**-> 989			span->data.list_size = (*cache)->data.list_size + 1;**
   990		else
   991			span->data.list_size = 1;
   992		*cache = span;

I'm not familiar with this code, yet, but after a little bit of debugging the crash seems to possibly be related to SPAN_CLASS_COUNT being equal to 1 for a 16KB page, and the code not being able to handle that case.

If I increase the value of SPAN_ADDRESS_GRANULARITY proportionally, to (4 * 65536), it no longer crashes.  Is that actually an appropriate fix?

Cheers,
James

**Comment by MJansson** [comment]
That fix is not enough unfortunately, as a few of the structure setups (wrongly) assumed a 4KiB page size. The page size was a mixup between the internal expected minimum "unit" and the system page size, which should really be separate.

I'm going to refactor the setup a bit to not have this internal minimum unit and instead work with a runtime determined system page size.

**Comment by jritts-g** [comment]
Thanks very much for the fast response.  In the meantime, what would be the problem with me using the default 4KB in rpmalloc on this platform?  I imagine it might just waste partial pages which are mapped for smaller classes of allocations...?

**Comment by MJansson** [comment]
Yep, that would be the result.

However, I finished my implementation of allowing system (or configured, in case you want to use your own memory mapping/unmapping) page sizes between 512 and 16384 (2^9 to 2^14) bytes. Also, if no page size is given it will use system calls to determine the page size (which should then be 16384 on modern 64bit ARM iOS devices).

You can test it by using the configurable-page-size branch -
 https://github.com/rampantpixels/rpmalloc/tree/configurable-page-size

**Comment by MJansson** [comment]
If you do try it out, please report back what the results are. I will run the benchmark suite on a set of devices to test it myself before merging to develop branch (and later to the next release), but it will take a while.

**Comment by jritts** [comment]
I tried that branch on Windows 10 64b, OSX 10.13.2, Android N 64b and iOS 11.2.1 - no issues so far.  _memory_page_size is 16384 on iOS, 4096 everywhere else as expected.  Thank you for the fix!

**Comment by MJansson** [comment]
Thank you for the confirmation. My tests were successful as well, have merged to develop branch.
