### ISSUE TITLE
out of bounds read in _memory_allocate_large_from_heap

### ISSUE THREAD

**Issue by velkyel** [rampantpixels/rpmalloc#46]
https://github.com/rampantpixels/rpmalloc/blob/82fbcc0af8f46d640024dbb5f612d7b7f0552ec5/rpmalloc/rpmalloc.c#L915

...there is wrong testing order.  (idx < LARGE_CLASS_COUNT) have to be before !heap->large_cache[idx] because if idx == LARGE_CLASS_COUNT (after iteration) then you read from undefined memory (out-of-bounds).

**Comment by MJansson** [comment]
Thanks, I will fix that asap

**Comment by MJansson** [comment]
The order is actually intented, but it's the range limit that is wrong (since the initial idx is guaranteed to be less than LARGE_CLASS_COUNT)

Fixed in  f9b1bb4

**Comment by velkyel** [comment]
thanks for fast reaction.  anyway there is corner case when:
```
idx = 31;    // when num_spans = 32 -> 	size_t idx = num_spans - 1;

	//Step 1: Check if cache for this large size class (or the following, unless first class) has a span
	while (!heap->large_cache[idx] && (idx < LARGE_CLASS_COUNT) && (idx < num_spans + 1))
		++idx;
	span_t* span = heap->large_cache[idx];
// ...there is reading out-of-bounds too and span is undefined:
if (span) {
```

**Comment by velkyel** [comment]
yes, fix https://github.com/rampantpixels/rpmalloc/commit/f9b1bb4f100401b54de193bf8f75218db403763f looks good.  thanks.

**Comment by MJansson** [comment]
Will add a test case for this (iterating small, medium and larg size buckets and allocating a block of memory of given size directly after initializing allocator, i.e empty caches)

**Comment by MJansson** [comment]
Tests added
