### ISSUE TITLE
Handle zero sized allocations

### ISSUE THREAD

**Issue by incrediblejr** [rampantpixels/rpmalloc#47]
Current implementation does not handle zero sized allocations in 'default' configuration as it will trigger an out of bounds read when looking up class id (https://github.com/rampantpixels/rpmalloc/blob/master/rpmalloc/rpmalloc.c#L722).

As this is implementation defined (as far as I know), I'll defer to you how to handle this.

Personally I would prefer it to return non-null and can see the reasoning behind handling it by forcing a minimum allocation size of one byte _or_ with a special non-null pointer (each with their own trade-offs).

**Comment by incrediblejr** [comment]
Giving it some more thought I think the correct solution is to return a special non-null pointer for the same reasons outlined here: https://lwn.net/Articles/236920/

**Comment by MJansson** [comment]
Fixed in 6357bf5 on develop branch, will make a new 1.2.3 release soon to include this
