### ISSUE TITLE
question on thread api

### ISSUE THREAD

**Issue by velkyel** [rampantpixels/rpmalloc#49]
When I'm including new.cc in my project then I don't have to call rpmalloc_thread_initialize() on new or new [] thanks to initialize() function.   I have to always call rpmalloc_thread_finalize() myself when I close/destroy my thread, right?

**Comment by MJansson** [comment]
Yes. Depending on your use of allocations/free during global initialization/finalization you could possibly use pthread_key_create with a destructor or similar platform specific API to do this automagically.
