### ISSUE TITLE
Comparison with the other tiny lockfree allocator

### ISSUE THREAD

**Issue by ivan-tkatchev** [rampantpixels/rpmalloc#5]
Hi. We have another tiny lockfree allocator, albeit written in C++: https://github.com/Begun/lockfree-malloc

Would it be terribly hard to add it to the benchmarks too?

**Comment by MJansson** [comment]
Will do

**Comment by MJansson** [comment]
lockfree-malloc has been added to the benchmark repo and included in the runall script, will be included in the benchmark results for the next release

https://github.com/rampantpixels/rpmalloc-benchmark
