### ISSUE TITLE
Random access violations in custom test on windows

### ISSUE THREAD

**Issue by brandon-kohn** [rampantpixels/rpmalloc#51]
Hello,

I've been trying to do some testing with your library and have run into issues while running the following:

```
std::size_t nAllocations = 1000000;
TEST(rpmalloc_test_suite, cross_thread_bench)
{
    rpmalloc_initialize();
    using namespace stk::thread;
    std::size_t nOSThreads = std::thread::hardware_concurrency();
    work_stealing_thread_pool<moodycamel_concurrent_queue_traits> pool(rpmalloc_thread_initialize, rpmalloc_thread_finalize, nOSThreads);
    using future_t = boost::future<void>;
    std::vector<future_t> futures;
    futures.reserve(nAllocations);
    {
        GEOMETRIX_MEASURE_SCOPE_TIME("rpmalloc_cross_thread_32_bytes");
        for (size_t i = 0; i < nAllocations; ++i)
        {
            auto pAlloc = rpmalloc(32);
            futures.emplace_back(pool.send(i++%pool.number_threads(),
                [pAlloc]()
                {
                    rpfree(pAlloc);
                }));
        }

        boost::for_each(futures, [](const future_t& f) { f.wait(); });
    }
    rpmalloc_finalize();
}
```
Essentially, allocate the block in one thread and deallocate in another. I get random access violations though. Does my usage seem correct?

**Comment by brandon-kohn** [comment]
If it helps, you can get my full test by building the following:

https://github.com/brandon-kohn/simulation_toolkit/tree/feature/rpmalloc

**Comment by MJansson** [comment]
Are you using the malloc/free and new/delete wrappers? If so, that could be the issue, try only building the core lib with only rpmalloc.c

You can also try the latest develop branch to see if the problem persists. I noticed a couple of issues in the 1.2.2 release that I've fixed, and I'm preparing a new 1.3.0 release but it's still a couple of days away.

**Comment by MJansson** [comment]
But the usage seems ok, the important part is the rpmalloc_initialize/rpmalloc_finalize completely encompassing the use of the library, and that each thread has rpmalloc_thread_initialize/rpmalloc_thread_finalize on entry/exit.

**Comment by MJansson** [comment]
Also, if you could post a callstack of an access violation that would be helpful

**Comment by MJansson** [comment]
Actually, if you could try the release/1.3.0 branch it would be really helpful

**Comment by brandon-kohn** [comment]
It happens in that branch. I'm trying to get a stack, but it only happens in my optimized build. It's a structured exception caused by an integer being divided by zero if that helps.

**Comment by brandon-kohn** [comment]
Another note is that if I put a sleep between the thread pool initialization (thus the calls of rpmalloc_thread_initialize) and the first call to rpmalloc, the issue doesn't seem to happen. This might suggest a data race between the thread initialization and something under the rpmalloc call.

**Comment by MJansson** [comment]
Thanks, I will try to replicate the issue using your repo

**Comment by MJansson** [comment]
Can't seem to get boost, cmake and your repo to play nice on my system (I never use neither boost nor cmake normally). It fails to find boost in the libcds cmake step. Also, is googletest supposed to build using mingw/gcc?

**Comment by brandon-kohn** [comment]
If you're using the sudo command to build it.. be sure to use the `-E` switch to bring the BOOST_ROOT environment over. That got me a lot, so maybe it applies to your situation. I think you can build it however you like. I've built it on gcc linux, visual studio, and xcode. All of it should just work.

**Comment by MJansson** [comment]
It doesn't seem to work on my Windows machine, I run the b2 builder with the arguments listed in your readme, point BOOST_ROOT to C:\Boost and run update.bat

```
D:\simulation_toolkit>set BOOST_ROOT=C:\Boost

D:\simulation_toolkit>update.bat d:\simulation_toolkit_install Ninja
From https://github.com/brandon-kohn/simulation_suite
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/simulation_toolkit/cmake.build.release/googletest-download
[1/6] Performing update step for 'googletest'
Current branch master is up to date.
[2/6] No configure step for 'googletest'
[3/6] No build step for 'googletest'
[4/6] No install step for 'googletest'
[5/6] No test step for 'googletest'
[6/6] Completed 'googletest'
-- Clipper version 6.4.2.
-- NLopt version 2.5.0
-- Poly2tri version 1.0.0.
CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  libcds/CMakeLists.txt:30 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  libcds/CMakeLists.txt:30 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  libcds/CMakeLists.txt:30 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  libcds/CMakeLists.txt:30 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  libcds/CMakeLists.txt:30 (find_package)


-- Could NOT find Boost
-- Binary output path: D:/simulation_toolkit/cmake.build.release/libcds/bin
C++ std: -std=c++11 (default)
Build type -- release
Compiler version: GNU 4.8.2
System: Windows version: 10.0.16299
Target architecture: x86_64
Compiler flags:  -O3 -DNDEBUG -std=c++11;-mcx16 -Wall;-Wextra;-pedantic;-Wno-unused-local-typedefs
Exe flags:
Boost: Using CMake-fied boost
...
````

and then it goes downhill from there with compile errors due to missing boost. Dunno why it picks gcc over msvc toolchain.

**Comment by brandon-kohn** [comment]
Let me try to replicate what you've done. What was the command you issued to build boost?
Was it?

```
b2 toolset=<toolset> address-model=64 link=static,shared threading=multi --layout=versioned --with-system --with-thread --with-fiber --with-context install
```

**Comment by brandon-kohn** [comment]
The problem is the version of cmake doesn't know how to find the version of boost you've got. It's probably a new boost? 1.66 or greater?

https://gitlab.kitware.com/cmake/cmake/issues/17575

**Comment by MJansson** [comment]
Ah, yes, I was using 1.66. Will try again with 1.65.1 like in your readme

**Comment by brandon-kohn** [comment]
Ok, I'll try develop.

**Comment by brandon-kohn** [comment]
That does indeed seem to have sorted the issue. Cheers ;)
