### ISSUE TITLE
rpmalloc related segfaults with ksplashqml and Networkmanager(glib)

### ISSUE THREAD

**Issue by justanerd** [rampantpixels/rpmalloc#52]
Hi, I tried rpmalloc for my whole linux system and I got some segfaults.
The first one is from a qt program and the second one is from Networkmanager and is glib related.
I hope this is enough to find die bugs If not just comment here.

```
ksplashqml
#0  0x00007f5ad84b80a7 in _memory_deallocate_large_to_heap (heap=0x7f5ad0dc0000, span=0x7f5acc060000) at rpmalloc/rpmalloc.c:1161
#1  0x00007f5ad5ef8621 in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#2  0x00007f5ad418bbe3 in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#3  0x00007f5ad418ce00 in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#4  0x00007f5ad414eb89 in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#5  0x00007f5ad4151921 in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#6  0x00007f5ad5f432dd in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#7  0x00007f5ad84cec53 in ?? () from /lib64/ld-linux-x86-64.so.2
#8  0x00007f5ad71ce030 in ?? () from /lib64/libc.so.6
#9  0x00007f5ad71ce11a in exit () from /lib64/libc.so.6
#10 0x00007f5ad71aba6e in __libc_start_main () from /lib64/libc.so.6
#11 0x00000000004055da in _start ()


#0  _memory_allocate_from_heap (heap=0x7ffbf4120000, size=<optimized out>) at rpmalloc/rpmalloc.c:747
747             if (active_block->free_count) {
[Current thread is 1 (Thread 0x7ffbf492c700 (LWP 153212))]
(gdb) bt
#0  _memory_allocate_from_heap (heap=0x7ffbf4120000, size=<optimized out>) at rpmalloc/rpmalloc.c:747
#1  _memory_allocate (size=<optimized out>) at rpmalloc/rpmalloc.c:1272
#2  0x00007ffbf719457f in g_malloc (n_bytes=16) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmem.c:96
#3  0x00007ffbf719487b in g_malloc_n (n_blocks=2, n_block_bytes=8) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmem.c:339
#4  0x00007ffbf71cec59 in g_variant_new_dict_entry (key=0x7ffbf40a4260, value=0x7ffbf3321600) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gvariant.c:925
#5  0x00007ffbf73bd64f in parse_value_from_blob (buf=0x7ffbf492ba40, type=0x7ffbf745aa51, just_align=0, indent=4, error=0x7ffbf492b848)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusmessage.c:1778
#6  0x00007ffbf73bd4ab in parse_value_from_blob (buf=0x7ffbf492ba40, type=0x7ffbf745aa50, just_align=0, indent=2, error=0x7ffbf492bb00)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusmessage.c:1721
#7  0x00007ffbf73bde9f in g_dbus_message_new_from_blob (blob=0x7ffbf40e0020 "l\002\001\001", blob_len=72, capabilities=G_DBUS_CAPABILITY_FLAGS_UNIX_FD_PASSING,
    error=0x7ffbf492bb00) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusmessage.c:2084
#8  0x00007ffbf73ca329 in _g_dbus_worker_do_read_cb (input_stream=0x7ffbf49f1130, res=0x7ffbf49c4e00, user_data=0x7ffbf49e01e0)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusprivate.c:721
#9  0x00007ffbf736ff7c in g_task_return_now (task=0x7ffbf49c4e00) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gtask.c:1145
#10 0x00007ffbf736ffd9 in complete_in_idle_cb (task=0x7ffbf49c4e00) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gtask.c:1159
#11 0x00007ffbf718e977 in g_idle_dispatch (source=0x7ffbf40f1520, callback=0x7ffbf736ffc1 <complete_in_idle_cb>, user_data=0x7ffbf49c4e00)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:5586
#12 0x00007ffbf718bf5d in g_main_dispatch (context=0x7ffbf49d00e0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3234
#13 0x00007ffbf718cdfe in g_main_context_dispatch (context=0x7ffbf49d00e0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3899
#14 0x00007ffbf718cfe2 in g_main_context_iterate (context=0x7ffbf49d00e0, block=1, dispatch=1, self=0x7ffbf6079ad0)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3972
#15 0x00007ffbf718d408 in g_main_loop_run (loop=0x7ffbf4a81140) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:4168
#16 0x00007ffbf73c9794 in gdbus_shared_thread_func (user_data=0x7ffbf4a81100) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusprivate.c:252
#17 0x00007ffbf71bbfcb in g_thread_proxy (data=0x7ffbf6079ad0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gthread.c:784
#18 0x00007ffbf6fb05ea in start_thread () from /lib64/libpthread.so.0
#19 0x00007ffbf6ee14bf in clone () from /lib64/libc.so.6
```

**Comment by MJansson** [comment]
Can you please try the release/1.3.0 branch?

**Comment by justanerd** [comment]
Ok now I get a new segfault.
#0  0x00007fc60ac704ac in _memory_heap_lookup (id=<optimized out>) at rpmalloc/rpmalloc.c:506
#1  _memory_deallocate_defer (heap_id=<optimized out>, p=<optimized out>) at rpmalloc/rpmalloc.c:1258
#2  _memory_deallocate (p=0x7fc607512020) at rpmalloc/rpmalloc.c:1309
#3  0x00007fc60a7876ce in g_free (mem=0x7fc607512020) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmem.c:191
#4  0x00007fc60a752798 in g_bytes_unref (bytes=0x7fc6072a36a0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gbytes.c:310
#5  0x00007fc60a7c991e in g_variant_unref (value=0x7fc60771ef90) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gvariant-core.c:638
#6  0x00007fc60a76af08 in g_hash_table_remove_all_nodes (hash_table=0x7fc60769bde0, notify=1, destruction=1)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/ghash.c:548
#7  0x00007fc60a76ba70 in g_hash_table_unref (hash_table=0x7fc60769bde0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/ghash.c:1099
#8  0x00007fc60a9adcb4 in g_dbus_message_finalize (object=0x7fc609669ad0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusmessage.c:485
#9  0x00007fc60a87bc7d in g_object_unref (_object=0x7fc609669ad0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gobject/gobject.c:3185
#10 0x00007fc60a9bd7e6 in message_to_write_data_free (data=0x7fc6074c16f0) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusprivate.c:872
#11 0x00007fc60a9be595 in write_message_cb (source_object=0x0, res=0x7fc6077f1b90, user_data=0x7fc6074c16f0)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusprivate.c:1319
#12 0x00007fc60a962f7c in g_task_return_now (task=0x7fc6077f1b90) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gtask.c:1145
#13 0x00007fc60a962fd9 in complete_in_idle_cb (task=0x7fc6077f1b90) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gtask.c:1159
#14 0x00007fc60a781977 in g_idle_dispatch (source=0x7fc607802b40, callback=0x7fc60a962fc1 <complete_in_idle_cb>, user_data=0x7fc6077f1b90)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:5586
#15 0x00007fc60a77ef5d in g_main_dispatch (context=0x7fc6095a0860) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3234
#16 0x00007fc60a77fdfe in g_main_context_dispatch (context=0x7fc6095a0860) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3899
#17 0x00007fc60a77ffe2 in g_main_context_iterate (context=0x7fc6095a0860, block=1, dispatch=1, self=0x7fc609669850)
    at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:3972
#18 0x00007fc60a780408 in g_main_loop_run (loop=0x7fc60963c580) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gmain.c:4168
#19 0x00007fc60a9bc794 in gdbus_shared_thread_func (user_data=0x7fc60963c540) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/gio/gdbusprivate.c:252
#20 0x00007fc60a7aefcb in g_thread_proxy (data=0x7fc609669850) at /var/tmp/portage/dev-libs/glib-2.52.3/work/glib-2.52.3/glib/gthread.c:784
#21 0x00007fc60a5a35ea in start_thread () from /lib64/libpthread.so.0
#22 0x00007fc60a4d44bf in clone () from /lib64/libc.so.6

**Comment by justanerd** [comment]
Here is the backtrace for the first problem with the 1.3.0 branch.
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _memory_span_list_doublelink_remove (head=0x7f8cba4a09e0, span=span@entry=0x7f8cb9990000) at rpmalloc/rpmalloc.c:724
724                     prev_span->next_span = next_span;
(gdb) bt
#0  _memory_span_list_doublelink_remove (head=0x7f8cba4a09e0, span=span@entry=0x7f8cb9990000) at rpmalloc/rpmalloc.c:724
#1  0x00007f8cc1b79d42 in _memory_deallocate_to_heap (heap=0x7f8cba4a0000, span=0x7f8cb9990000, p=p@entry=0x7f8cb9994fa0) at rpmalloc/rpmalloc.c:1082
#2  0x00007f8cc1b79f21 in _memory_deallocate (p=p@entry=0x7f8cb9994fa0) at rpmalloc/rpmalloc.c:1226
#3  0x00007f8cc1b7ac47 in rpfree (ptr=ptr@entry=0x7f8cb9994fa0) at rpmalloc/rpmalloc.c:1727
#4  0x00007f8cc1b7b19d in free (ptr=0x7f8cb9994fa0) at rpmalloc/malloc.c:320
#5  0x00007f8cbf5bc621 in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#6  0x00007f8cbd7ece9b in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#7  0x00007f8cbd7eee68 in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#8  0x00007f8cbd8654ca in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#9  0x00007f8cbd7e051e in ?? () from /usr/lib64/libnvidia-glcore.so.390.25
#10 0x00007f8cbf5b0e69 in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#11 0x00007f8cbf60747a in ?? () from /usr/lib64/opengl/nvidia/lib/libGL.so.1
#12 0x00007f8cc1b91c53 in ?? () from /lib64/ld-linux-x86-64.so.2
#13 0x00007f8cc0892030 in ?? () from /lib64/libc.so.6
#14 0x00007f8cc089211a in exit () from /lib64/libc.so.6
#15 0x00007f8cc086fa6e in __libc_start_main () from /lib64/libc.so.6
#16 0x00000000004055da in _start ()
```

**Comment by MJansson** [comment]
Thanks, I'll do some local testing as system wide malloc replace to see what I can find

**Comment by MJansson** [comment]
Try the latest release/1.3.0 branch, seems pretty stable on my Yakkety Yak system at least as a system wide ld.so.preload

However, it can cause issues if a process does weird stuff, like allocating memory during process exit global destructors (had one crash where zeitgeist-datahub did calloc in one thread while the other thread was running libc __GI_exit exit handlers). This is not supported by rpmalloc. If you do get crashes, check stacktrace of all threads to make sure it's not during process cleanup like this example.

**Comment by MJansson** [comment]
Or, try the test/linux-pthread-heap-key branch which uses a pthread key for thread local storage and additional guards for allocations during process termination

**Comment by MJansson** [comment]
Closing this as any remaining issues are due to global destructor ordering, something rpmalloc does not currently aim to deal with.
