### ISSUE TITLE
WebAssembly page_size

### ISSUE THREAD

**Issue by carlokok** [rampantpixels/rpmalloc#54]
Hi,

On WebAssembly the size of a "page"(minimal allocation block) is 64k. setting page_size on memory config to 65536 doesn't work because of 
```
	if (_memory_page_size > (16 * 1024))
		_memory_page_size = (16 * 1024);
```

Is it safe to just change that check to 64?

When I do that it fails with a sigsegv here:
```
_memory_deallocate_to_heap
_memory_deallocate
free
``` 

This might be a bug in my compiler though. Is there anything else that needs changing to make it work?

**Comment by MJansson** [comment]
The current implementation cannot handle memory page sizes of 64KiB, will look into supporting that

**Comment by carlokok** [comment]
Thanks. If there's anything I can do to help (like test?) let me know.

**Comment by MJansson** [comment]
You could try setting ENABLE_ASSERT to 1 in rpmalloc.c and see if you hit any assert before the segfault when running with page size of 64KiB

**Comment by MJansson** [comment]
Do you have an example where this is happening? I've tested running the benchmarks with 64KiB page size and had no issues so far.

Are you using the latest develop branch (or 1.3 release)?

**Comment by carlokok** [comment]
I must have done something wrong in my original "mmap" implementation, my apologies. My current implementation (That allows any page size and just keeps increasing the pointer) works fine when rpmalloc's page size is set to 65536. So with the adjustment above this works for me.

**Comment by MJansson** [comment]
Great, I'll do more comprehensive stress tests and remove the artificial page size limit asap

**Comment by MJansson** [comment]
The feature/64k-pages branch now has the page size limit set to 64KiB

**Comment by MJansson** [comment]
btw, if you have any webassembly example running with rpmalloc I would be very interested in looking at it. Feel free to post something here, or ping me on twitter @maniccoder

**Comment by carlokok** [comment]
Not exactly. We use it inside our runtime library for our Elements compiler (native target); currently only on WebAssembly where we have our own GC.

https://github.com/remobjects/IslandRTL/blob/master/Source/rpmalloc.pas

gc:
https://github.com/remobjects/IslandRTL/blob/master/Source/SimpleGC.pas

We don't currently have a sample up online.
