### ISSUE TITLE
Option to disable unmapping

### ISSUE THREAD

**Issue by carlokok** [rampantpixels/rpmalloc#55]
I'd like to request a feature to disallow unmapping; on wasm only "growing" is supported; so giving back doesn't make sense there.

**Comment by MJansson** [comment]
For now you could simply ignore the unmap call by using and empty function if you're using a custom memory_map/memory_unmap functions in the rpmalloc config.

**Comment by carlokok** [comment]
I'm doing that now; but won't that memory be effectively "lost" ?

**Comment by MJansson** [comment]
Ah, yes, it will be, and now I understand what you meant with this request :) Will look into it

**Comment by MJansson** [comment]
I will implement it as an unlimited global cache but normal thread cache.

Right now there is a 32-bit counter limitation on the global cache, but that would be all but a theoretical limit (2^32 span lists in cache, average something like 8 spans per list, 64KiB per span -> would be 2^52 bytes of cached memory before it wraps around). And the cache counter could easily be increased to a 64-bit value.

**Comment by MJansson** [comment]
You can try the feature/64k-pages branch and define `ENABLE_UNLIMITED_GLOBAL_CACHE` to 1 either in rpmalloc.c or in your build setup (and keep the  `ENABLE_UNLIMITED_CACHE` and `ENABLE_UNLIMITED_THREAD_CACHE` as it is, set to 0)

This will keep the default thread cache but set an unlimited global cache, effectively never unmapping any memory pages.

The memory will still be unmapped at allocator finalization, but you could just provide a dummy empty unmap function for that purpose.

**Comment by MJansson** [comment]
Ah, so you want to use the default mmap implementation (not provide your own in map/unmap callbacks in rpmalloc_config_t), but disallow calling munmap altogether?

**Comment by MJansson** [comment]
Added an option to disable unmap calls, set `DISABLE_UNMAP` to 1 in https://github.com/rampantpixels/rpmalloc/blob/feature/64k-pages/rpmalloc/rpmalloc.c#L53

**Comment by carlokok** [comment]
this is working nicely for us, thanks!
