### ISSUE TITLE
Endless loop if rpmalloc is compiled with MSVC for 32-bit targets

### ISSUE THREAD

**Issue by migra-leutek** [rampantpixels/rpmalloc#71]
I changed rpmalloc from a static library into a shared library so that it can be used in our application.

Therefore I have done the following things:
  - changed the configuration type from "static library (.lib)" to "dynamic library (.dll)" 
  - added the following code in rpmalloc.h
```
    #ifdef RPMALLOC_EXPORT
      # define RPMALLOC_API __declspec(dllexport)
    #else
      # define RPMALLOC_API __declspec(dllimport)
    #endif
```
  - replaced "extern " through "extern RPMALLOC_API "
  - added RPMALLOC_EXPORT to the preprocessor directive in project "rpmalloc" 
  - replaced _LIB through _DLL in preprocessor directive

When the program "test" is now executed and a thread calls "rpmalloc_thread_finalize" the program hangs in an endless loop.

I attached the changed source code.

Do you have any idea why this happens ?

![endless_loop](https://user-images.githubusercontent.com/39116563/40039792-16ad0064-5818-11e8-8a7d-a43d29a133d3.png)
[rpmalloc-1.3.1.zip](https://github.com/rampantpixels/rpmalloc/files/2003644/rpmalloc-1.3.1.zip)

**Comment by migra-leutek** [comment]
It’s your test program which comes with rpmalloc.

Von: Mattias Jansson [mailto:notifications@github.com]
Gesendet: Dienstag, 15. Mai 2018 08:23
An: rampantpixels/rpmalloc <rpmalloc@noreply.github.com>
Cc: Graf, Michael <Michael.Graf@leutek.de>; Author <author@noreply.github.com>
Betreff: Re: [rampantpixels/rpmalloc] Endless loop if rpmalloc is executed in a shared library (#71)


Could you share the code for your test program as well?

**Comment by MJansson** [comment]
Ah, fair enough, I'll have a look at it

**Comment by MJansson** [comment]
Works fine for me. Make sure you change the C/C++ runtime to Multi-threaded DLL or Multi-threaded Debug DLL depending on which configuration you're building, in both rpmalloc and test projects.

![rpmalloc-config](https://user-images.githubusercontent.com/3316562/40041530-97b20ed8-581e-11e8-86aa-2d21888f0062.png)

**Comment by MJansson** [comment]
I also change the output for the rpmalloc projects to bin directory instead of lib, to make sure it ends up alongside the test executable (if you tried building with ninja there might be an old DLL there that cannot be used for this test)

**Comment by migra-leutek** [comment]
I made the changes as you remarked:

-          Output directory (I copied it before manually)

-          C/C++ runtime to Multi-threaded DLL (this was wrong ☹)


In (Release|x64) and (Debug|x64) it runs as expected.
But in (Release|x86)  and (Debug|x86) it hangs in an endless loop in rpmalloc_thread_finalize.


Von: Mattias Jansson [mailto:notifications@github.com]
Gesendet: Dienstag, 15. Mai 2018 09:04
An: rampantpixels/rpmalloc <rpmalloc@noreply.github.com>
Cc: Graf, Michael <Michael.Graf@leutek.de>; Author <author@noreply.github.com>
Betreff: Re: [rampantpixels/rpmalloc] Endless loop if rpmalloc is executed in a shared library (#71)


I also change the output for the rpmalloc projects to bin directory instead of lib, to make sure it ends up alongside the test executable (if you tried building with ninja there might be an old DLL there that cannot be used for this test)

**Comment by MJansson** [comment]
Made a fix for 32-bit MSVC builds, it was using the 64-bit pointer atomic CAS instead of 32-bit as it should. 

Note though that the test will probably crash due ot it mapping more virtual memory than supported in 32-bit address space.

**Comment by migra-leutek** [comment]
Thanks.

Von: Mattias Jansson [mailto:notifications@github.com]
Gesendet: Dienstag, 15. Mai 2018 12:55
An: rampantpixels/rpmalloc <rpmalloc@noreply.github.com>
Cc: Graf, Michael <Michael.Graf@leutek.de>; Author <author@noreply.github.com>
Betreff: Re: [rampantpixels/rpmalloc] Endless loop if rpmalloc is executed in a shared library (#71)


Made a fix for 32-bit MSVC builds, it was using the 64-bit pointer atomic CAS instead of 32-bit as it should.

Note though that the test will probably crash due ot it mapping more virtual memory than supported in 32-bit address space.
