### ISSUE TITLE
rpmalloc.c doesn't compile as C++

### ISSUE THREAD

**Issue by waddlesplash** [rampantpixels/rpmalloc#80]
Nearly all the errors are related to implicit-casting `void*` to some other type. Would you accept a pull request fixing these by adding explicit casts? If so, I'll be happy to do the work.

**Comment by waddlesplash** [comment]
(I'm investigating integrating rpmalloc as the default allocator in Haiku's libc, and doing so would be easier if I could compile rpmalloc as C++ instead of C.)

**Comment by MJansson** [comment]
I've given this some thought and will keep the repo targeted at C compilation (the header should already be usable to C++ source). Suggested solution would be to add a language switch to your build system to always compile rpmalloc.c as C and not C++
