### ISSUE TITLE
Problem when building rpmalloc in 32bit on linux

### ISSUE THREAD

**Issue by hichem001** [rampantpixels/rpmalloc#87]
Hello,
On linux, by default the building architecture is x86-64 and that's working fine. I tried to build for x86 by excuting:
./configure.py -a x86
ninja
I'm getting the following error (there are a lot of them):

[7/44] CC rpmalloc/rpmalloc.c
FAILED: build/ninja/linux/debug/x86/rpmalloc-7c2f09b/rpmalloc-65d008a.o
clang -MMD -MT build/ninja/linux/debug/x86/rpmalloc-7c2f09b/rpmalloc-65d008a.o -MF build/ninja/linux/debug/x86/rpmalloc-7c2f09b/rpmalloc-65d008a.o.d -I.  -DRPMALLOC_COMPILE=1 -funit-at-a-time -fstrict-aliasing -fno-math-errno -ffinite-math-only -funsafe-math-optimizations -fno-trapping-math -ffast-math -D_GNU_SOURCE=1 -W -Werror -pedantic -Wall -Weverything -Wno-padded -Wno-documentation-unknown-command -std=c11 -m32 -DBUILD_DEBUG=1 -g  -c rpmalloc/rpmalloc.c -o build/ninja/linux/debug/x86/rpmalloc-7c2f09b/rpmalloc-65d008a.o
rpmalloc/rpmalloc.c:1278:31: error: implicit conversion changes signedness: 'ptrdiff_t' (aka 'int') to 'unsigned int' [-Werror,-Wsign-conversion]
                        return size_class->size - (pointer_diff(p, blocks_start) % size_class->size);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
rpmalloc/rpmalloc.c:201:37: note: expanded from macro 'pointer_diff'
#define pointer_diff(first, second) (ptrdiff_t)((const char*)(first) - (const char*)(second))
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

any help please?

**Comment by mjansson** [comment]
Should be fixed now with https://github.com/rampantpixels/rpmalloc/commit/76876ad43f7781bfb870a10f9c9b913c0d64d44f

**Comment by hichem001** [comment]
fixed! thanks
