### ISSUE TITLE
is it possible to check that a memory is allocated by rpmalloc or not?

### ISSUE THREAD

**Issue by hichem001** [rampantpixels/rpmalloc#90]
Hello,
As I'm doing some tests with rpmalloc, I found that it's not capable to free a memory allocated with another allocator. So I'm posting this question: is there a way to know whether a memory is allocated with rpmalloc or not (a kind of signature or header that we can check)?

Thanks!

**Comment by mjansson** [comment]
No, there is no magic header and the allocator expects the caller to pass in valid data, there is no hand-holding going on.
